### ISSUE TITLE
Governor Bravo proposals to change variables in NounsAuctionHouse.sol

### ISSUE THREAD

**Issue by jackdishman** [bostondao/nouns-monorepo-fork#10]
Referring to branch [`update-duration`, ](https://github.com/bostondao/nouns-monorepo-fork/pull/7/files) the methods to change auction variables are only callable by the owner address. We are looking to modify the following methods to enable GB proposals to execute after a vote has passed:

- setTimeBuffer
- setReservePrice
- setMinBidIncrementPercentage
- setDuration

Questions: Can a Governor Bravo passed vote execute a method from the `owner` address (multi-sig) that deployed the contracts?

Also open to other ideas to make these variables configurable after a successful proposal passes.

Thanks in advance!

**Comment by colink14110476** [comment]
> Questions: Can a Governor Bravo passed vote execute a method from the `owner` address (multi-sig) that deployed the contracts?

Do you mean, execute a nounsHouseAuction method like `setDuration`? If so, then if its an `onlyOwner` method, then no since the Governor Bravo is not the owner (multi-sig). We could expand the restriction from `onlyOwner` to `onlyAdmins` and have the GovernorBravo and MultiSig both be admins.

**Comment by jackdishman** [comment]
> expand the restriction from onlyOwner to onlyAdmins and have the GovernorBravo and MultiSig both be admins

This sounds like the ideal approach, thanks @colink14110476 !
