### ISSUE TITLE
Fix failed actions in GitHub workflow

### ISSUE THREAD

**Issue by jackdishman** [bostondao/nouns-monorepo-fork#8]
Currently, the `main` branch and all new PRs are failing the [GitHub actions](https://github.com/bostondao/nouns-monorepo-fork/actions), specifically the first _Build and Test_

Console error:
```
Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +373ff086bd194ddf1490b0ded14a51cdb778356f:refs/remotes/origin/master
  remote: fatal: bad tree object af6719ecd98ebc47613d075e2c3bbbc50fccda09        
  Error: fatal: protocol error: bad pack header
  The process '/usr/bin/git' failed with exit code 128
  Waiting 15 seconds before trying again
```

Any help would be greatly appreciated!

**Comment by colink14110476** [comment]
```
Failed to compile.

src/components/Banner/index.tsx
  Line 4:8:  'calendar_noun' is defined but never used  @typescript-eslint/no-unused-vars
  Line 5:8:  'Noun' is defined but never used           @typescript-eslint/no-unused-vars

src/components/NavBar/index.tsx
  Line 3:8:  'logo' is defined but never used  @typescript-eslint/no-unused-var
```

Potential fix:
In packages/noun-webapp/src/components/... 
Remove the not used variable.

I don't know if this is just a warning or what actually causes the Failed compilation tho.

**Comment by jackdishman** [comment]
I removed the unused imports listed above in a local branch `error-fixes` and now getting this error when pushing to origin:
```
jackdishman@Jacks-MBP nouns-monorepo-fork % git push --set-upstream origin error-fixes
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 10 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 886 bytes | 886.00 KiB/s, done.
Total 10 (delta 8), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas:  75% (6/8), completed with 6 local objects.
remote: fatal: pack has 2 unresolved deltas
To https://github.com/bostondao/nouns-monorepo-fork.git
 ! [remote rejected]   error-fixes -> error-fixes (failed)
error: failed to push some refs to 'https://github.com/bostondao/nouns-monorepo-fork.git'
```

I believe it's related to the error above, as both reference **packs** (_bad pack header_ & _pack has 2 unresolved deltas_)

**Comment by colink14110476** [comment]
Hmm weird. I won't be able to test locally for 3 days. Some things I would do is diff this repo against the NounsDao repo and see if there are any relevant git changes. 
Can you confirm if you create a new clone locally and try to push anything, this occurs as well?

**Comment by jackdishman** [comment]
It's odd because this fork is up to date with the base Nouns repo, aside from the 7 commits ahead that are all UI-related changes here: https://github.com/nounsDAO/nouns-monorepo/compare/master...bostondao:nouns-monorepo-fork:master

Also getting the same ** fatal: pack has 2 unresolved deltas** when creating a new clone :/
